 apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: ps-retail-cartservice-hpa
spec:
 maxReplicas: 5
 minReplicas: 1
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: ps-retail-cartservice-deployment
 targetCPUUtilizationPercentage: 70
