{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "ps-retail-cartservice.serviceAccountName" . }}
  labels:
{{ include "ps-retail-cartservice.labels" . | indent 4 }}
{{- end -}}
