# Service - LoadBalancer
# # pb-service -lb.yml
apiVersion: v1
kind: Service
metadata:
  name: ps-retail-cartservice-service
  labels:
    app: tga-cart-service-pipeline
spec:
  selector:
    app: tga-cart-service-pipeline
  type: LoadBalancer
  ports:
  - nodePort: 32750
    port: 8080
    targetPort: 8080
